### ISSUE TITLE
P(k) calculation hangs for certain cosmologies

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#446]
I just found a case where with master I tried to compute the power spectrum for a particular cosmology and just got an indefinite hanging and / or terrible memory-related errors. 

It's kind of a weird cosmology because I was computing numerical derivatives for Fisher forecasting but it's not totally crazy:
Omega_c = 0.205, Omega_b = 0.05, h = 0.68, sigma8=0.83, n_s = 0.96

I am wondering if CLASS fails for this cosmology, haven't had a chance to try it directly yet by I will do so. @damonge do you have any experience with whether CLASS is likely to have problems with this cosmology?

**Comment by elisachisari** [comment]
Any chance this is fixed in CLASS 2.7, which we are hopefully soon merging?

**Comment by NiallJeffrey** [comment]
I've had a similar problem with this (Omega_c=0.206, Omega_b=0.044, h=0.7, sigma8=0.8, n_s=0.95) and it also affects the angular power spectrum.  As the emulator doesn't work for the lensing Cl calculation (https://github.com/LSSTDESC/CCL/issues/618) it means I can't think of a way to get around this problem.

**Comment by elisachisari** [comment]
With CAMB implementation in v2, can we now close this? @c-d-leonard?

**Comment by c-d-leonard** [comment]
Having CAMB as our default definitely helps (provided there aren't similar as-yet-undiscovered issues with that), but since we still do support CLASS, I think this is still an issue, if less urgent?

**Comment by c-d-leonard** [comment]
It would be great if someone could check if this is still the case for class, I'm marking this as new-contributor-friendly for someone to perform that check.

**Comment by damonge** [comment]
Just tested that this doesn't happen anymore
```
>>> cosmo = ccl.Cosmology(Omega_c=0.205, Omega_b=0.05, h=0.68, sigma8=0.83, n_s=0.96, transfer_function='boltzmann_class'); print(ccl.sigma8(cosmo))
0.8300000000000001
```
So closing
