### ISSUE TITLE
fftlog correlation test fails in master 

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#533]
I am finding that currently in master C test 67, `corrs:analytic_fftlog`, fails. The error I get is the following: 

```
TEST 67/91 corrs:analytic_fftlog WARNING: ERROR: Cannot make log-spaced array with 0 points - need at least 2

ERROR 1026: ccl_correlation.c: ccl_tracer_corr_fftlog ran out of memory
```
Is this something weird with my setup at the moment or can anyone else reproduce this?

**Comment by philbull** [comment]
Travis is reporting that `master` is passing tests.

**Comment by c-d-leonard** [comment]
Does travis run the C tests or just python? @elisachisari and @sjoudaki have now reproduced this behaviour.

**Comment by c-d-leonard** [comment]
Okay, weird. Maybe Elisa or Shahab can sit with you to have a look? Or I'm happy to try to pair debug this via a slack call or something.

**Comment by sjoudaki** [comment]
I don't have an issue with the c unit test, only via the notebook do I obtain:

"CCLError: Error CCL_ERROR_LINSPACE: ccl_correlation.c: ccl_tracer_corr_fftlog ran out of memory"

**Comment by sjoudaki** [comment]
sorry, accidental closure.

I don't have an issue with the c unit test, only via the notebook do I obtain:

"CCLError: Error CCL_ERROR_LINSPACE: ccl_correlation.c: ccl_tracer_corr_fftlog ran out of memory"

Happy to chat with David more closely.

**Comment by elisachisari** [comment]
I'm away from my desk till Dec 8, but can connect remotely and share screen if it helps, @damonge.

**Comment by elisachisari** [comment]
@c-d-leonard @sjoudaki: We debugged this with @damonge. We think this is being caused by CCL looking for the wrong ccl_params.ini. To avoid this, could you please try to `make; make install; make uninstall; make install` and run the checks again? This fixed the issue for me in my computer.

**Comment by c-d-leonard** [comment]
@elisachisari Thanks! Yes, with this I now have that test passing (although I still have test 73 failing with:
`TEST 73/91 emu:model_5 ERROR 1032: ccl_power.c: ccl_cosmology_compute_power_class(): Error running CLASS spectra:spectra_init(L:1297) :error in spectra_pk(pba,ppt,ppm,pnl,psp);
=>spectra_pk(L:2785) :error in spectra_sigma(pba,ppm,psp,8./pba->h,0.,&(psp->sigma8));
=>spectra_sigma(L:28`
but I think this is being addressed by @philbull in PR #521 ?

**Comment by damonge** [comment]
It is, yes. We should leave this open until @sjoudaki confirms this also fixes his issue.

**Comment by c-d-leonard** [comment]
We agreed to go ahead and close this because @sjoudaki is unable to check this at the moment and we have confirmation from two different people who were seeing this error that it is fixed.

**Comment by sjoudaki** [comment]
Sorry Danielle, I did check this earlier today and chatted with David about it, my issue with the memory was never for the c unit test, but at the notebook level. There I obtained the analogous error:

"CCLError: Error CCL_ERROR_LINSPACE: ccl_correlation.c: ccl_tracer_corr_fftlog ran out of memory"

And, this has still not been fixed, even with the latest suggestion.

**Comment by sjoudaki** [comment]
Yes, after my latest message here, it now seems to be working. I guess we can put this aside for now, and hope the memory error does not reappear.

**Comment by damonge** [comment]
Don't think it's a memory error, just a problem with residual files. In any case I agree that the way the spline params are currently being set is not ideal (for one it makes use of static variables and can get very confused about where to look for the file). Hopefully this is something we cab improve soon.

**Comment by beckermr** [comment]
This just bit me in the ass too. Grrrrrr...
